# Generated by Django 6.1.1 on 2026-09-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsubmission',
            old_name='is_evaluated',
            new_name='passed',
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
