# Generated by Django 6.1.1 on 2026-09-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_is_evaluated_examsubmission_passed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='profiles.mentorcourse'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Optional — leave blank to assign to all enrolled students.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
